on: [push, pull_request, workflow_dispatch]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }}

  build:
    needs: cache
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
